[package]
name = "solana-bpf-logs-tracing"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
tracing = []
disabled = []
default = ["disabled"]

[dependencies]
quote = "1.0.40"
syn = { version = "2.0.104", features = ["full"] }
